USE [GestioEnfant]
GO

/****** Object:  Table [dbo].[Membre]    Script Date: 13/09/2023 15:19:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Membre](
	[Id] [int] NOT NULL IDENTITY,
	[NumDossier] [varchar](255) NOT NULL ,
	[Nom] [varchar](255) NOT NULL,
	[Prenom] [varchar](255) NOT NULL,
	[DateNaissance] [date] NOT NULL,
	[IGroupe] [int] NOT NULL,
	[IdBus] [int] NOT NULL,
 CONSTRAINT [PK_MEMBRE] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Membre]  WITH CHECK ADD  CONSTRAINT [Membre_fk0] FOREIGN KEY([IGroupe])
REFERENCES [dbo].[Groupe] ([IdGroupe])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[Membre] CHECK CONSTRAINT [Membre_fk0]
GO

ALTER TABLE [dbo].[Membre]  WITH CHECK ADD  CONSTRAINT [Membre_fk1] FOREIGN KEY([IdBus])
REFERENCES [dbo].[Bus] ([IdBus])
ON UPDATE CASCADE
GO

ALTER TABLE [dbo].[Membre] CHECK CONSTRAINT [Membre_fk1]
GO


